openapi: 3.0.0
info:
  title: Job-Listing
  description: Job-Listing app API
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: local server
paths:
  /listings:
    get:
      tags:
        - Listings
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
